Element.find_or_create_by(name: 'Blaze')
Element.find_or_create_by(name: 'Frost')
Element.find_or_create_by(name: 'Radiant')
Element.find_or_create_by(name: 'Shock')
Element.find_or_create_by(name: 'Umbral')